### Get All Users
GET http://localhost:3000/songs

### Get User Information
GET http://localhost:3000/songs/1

### Create a New User
POST http://localhost:3000/songs

### Update User Information
PUT http://localhost:3000/songs/1

### Delete User
DELETE http://localhost:3000/songs/1
